# .github/workflows/push-to-content-flow.yml
name: Sync main to content-flow

permissions:
    contents: write

on:
    push:
        branches:
            - main

jobs:
    branch-sync:
        uses: ScarlateAlves/store/.github/workflows/update-content.yml@main
        with:
            source-branch: main
            target-repo: user/content-flow
            target-branch: main
