# .github/workflows/push-to-content-flow.yml
name: Sync main to content-flow

permissions:
    contents: write
    pull-requests: write

on:
    push:
        branches:
            - main

jobs:
    branch-sync:
        uses: ScarlateAlves/store/.github/workflows/update-content.yml@main
        with:
            source: main
            target: content-flow
        secrets:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
